Add aurtool, font packages

diff --git a/bin/aurtool b/bin/aurtool
--- a/bin/aurtool
+++ b/bin/aurtool
@@ -2,35 +2,36 @@
 
 set -euo pipefail
 
-pkg=$1
-if [ -z "$pkg" ]; then
-  echo "Usage: aurtool <package>"
+if [ $# -lt 1 ]; then
+  echo "Usage: aurtool <package>..."
   exit 1
 fi
 
-tmp=$(mktemp -d -t aurtool-$pkg.XXXXXXXX)
+tmp=$(mktemp -d -t aurtool.XXXXXXXX)
 trap "rm -rf $tmp" EXIT
 
-installed_version=$(pacman -Q $pkg 2>/dev/null |cut -d' ' -f2 || echo '')
+for pkg in "$@"; do
+  installed_version=$(pacman -Q $pkg 2>/dev/null |cut -d' ' -f2 || echo '')
 
-curl -s "https://aur.archlinux.org/cgit/aur.git/snapshot/$pkg.tar.gz" \
-  | tar xzf - -C $tmp 2>/dev/null \
-  || (echo 'Failed to get AUR package.' && false)
+  curl -s "https://aur.archlinux.org/cgit/aur.git/snapshot/$pkg.tar.gz" \
+    | tar xzf - -C $tmp 2>/dev/null \
+    || (echo 'Failed to get AUR package.' && false)
 
-cd "$tmp/$pkg"
+  cd "$tmp/$pkg"
 
-ver=("${(@f)$(grep -E '^(epoch|pkg(ver|rel))=' PKGBUILD |sort |cut -d'=' -f2)}")
-if [ $#ver -eq 3 ]; then
-  next_version="${ver[1]}:${ver[3]}-${ver[2]}"
-else
-  next_version="${ver[2]}-${ver[1]}"
-fi
+  ver=("${(@f)$(grep -E '^(epoch|pkg(ver|rel))=' PKGBUILD |sort |cut -d'=' -f2)}")
+  if [ $#ver -eq 3 ]; then
+    next_version="${ver[1]}:${ver[3]}-${ver[2]}"
+  else
+    next_version="${ver[2]}-${ver[1]}"
+  fi
 
-if [ "$installed_version" = "$next_version" ]; then
-  echo "${pkg} ${next_version} is already installed."
-else
-  echo "Upgrading from ${pkg} ${installed_version}..."
-  makepkg -sri --needed
-fi
+  if [ "$installed_version" = "$next_version" ]; then
+    echo "${pkg} ${next_version} is already installed."
+  else
+    echo "Upgrading from ${pkg} ${installed_version}..."
+    makepkg -sri --needed
+  fi
 
-cd -
+  cd -
+done
